apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    database: k6
    isDefault: true
    editable: true
    jsonData:
      httpMode: GET
